Passive Checks
vatesfr/xo-server-nagios pull request #1
Opened 2016-12-01 15:17 UTC by badrAZ

2016-12-02 11:23 UTC, pdonias commented on README.md
> +the web iterface, see [the plugin documentation](https://xen-orchestra.com/docs/plugins.html). You can also test the configuration plugin if it works.
interface*

2016-12-02 11:23 UTC, pdonias commented on README.md
> +the web iterface, see [the plugin documentation](https://xen-orchestra.com/docs/plugins.html). You can also test the configuration plugin if it works.
"You can also test if the configuration plugin works."

2016-12-02 11:29 UTC, pdonias commented on src/index.js
> +    client.on('data', (data) => {
Parenthesis are not necessary when there is only one parameter.

2016-12-02 11:31 UTC, pdonias commented on src/index.js
> +    const version = 3
`size` and `version` could be declared as global variables.

2016-12-02 11:33 UTC, pdonias commented on src/index.js
> +    let result = []
Declare as `const`

2016-12-02 11:33 UTC, pdonias commented on src/index.js
> +    const chars = map.call(str, (x) => {
Parenthesis.

2016-12-07 13:46 UTC, olivierlambert requested changes

2016-12-07 13:46 UTC, olivierlambert commented on src/index.js
> +      const paquet = this._nscaPaquetBuilder(SIZE, VERSION, timestamp, iv, status, message, encoding)
Use `packet` word and not `paquet`

2016-12-07 13:46 UTC, olivierlambert commented on src/index.js
> +      const xorPaquetBuffer = new Buffer(this._xor(this._xor(this._stringToAsciiArray(paquet.toString(encoding)), this._stringToAsciiArray(iv)), this._stringToAsciiArray(this._conf.key)), encoding)
Same here, use `Packet`

2016-12-07 13:46 UTC, olivierlambert commented on src/index.js
> +  _nscaPaquetBuilder (size, version, timestamp, iv, status, message, encoding) {
Change all `Paquet` occurrences by `Packet`

2016-12-07 15:04 UTC, julien-f requested changes

2016-12-07 15:04 UTC, julien-f commented on README.md
> +the web interface, see [the plugin documentation](https://xen-orchestra.com/docs/plugins.html). You can also test if the configuration plugin works.
Remove the second sentence, it's not important to write this here.

2016-12-07 15:04 UTC, julien-f commented on README.md
> +This xo method is called to send a passive check to nagios and change the status of a service.
This does not explain what `status` and `message` should be.

2016-12-07 15:04 UTC, julien-f commented on src/index.js
> +import { Buffer } from 'buffer'
Named imports after default imports. (use SublimeText sort algorithm as a reference)

2016-12-07 15:04 UTC, julien-f commented on src/index.js
> +import crc32 from 'buffer-crc32'
Keep them sorted.

2016-12-07 15:04 UTC, julien-f commented on src/index.js
> +      description: 'The snca port'
*snca* should be in uppercase, right?

2016-12-07 15:04 UTC, julien-f commented on src/index.js
> +export const testSchema = {
Add a blank line between these exports.

2016-12-07 15:04 UTC, julien-f commented on src/index.js
> +    status: {
Is it necessary?

2016-12-07 15:04 UTC, julien-f commented on src/index.js
> +const SIZE = 720
Blank line before and *after* the separator.

2016-12-07 15:04 UTC, julien-f commented on src/index.js
>  class XoServerNagios {
Blank line before the class.

2016-12-07 15:04 UTC, julien-f commented on src/index.js
> +  _sendPassiveCheck (status, message) {
This method should returns a promise which resolves when the message has been sent or rejects in case of errors.

2016-12-07 15:04 UTC, julien-f commented on src/index.js
> +  _sendPassiveCheck (status, message) {
Use named parameters for future compatibility.

2016-12-07 15:04 UTC, julien-f commented on src/index.js
> +      const xorPaquetBuffer = new Buffer(this._xor(this._xor(this._stringToAsciiArray(paquet.toString(encoding)), this._stringToAsciiArray(iv)), this._stringToAsciiArray(this._conf.key)), encoding)
Break into multiple lines and use indentation to help readability.

2016-12-07 15:04 UTC, julien-f commented on src/index.js
> +  _nscaPaquetBuilder (size, version, timestamp, iv, status, message, encoding) {
Should not be a method as it does not use `this`.

2016-12-07 15:04 UTC, julien-f commented on src/index.js
> +  _stringToAsciiArray (str) {
Not a method.

2016-12-07 15:04 UTC, julien-f commented on src/index.js
> +  _xor (long, short) {
Not a method.

2016-12-07 15:04 UTC, julien-f commented on src/index.js
> +  _stringToAsciiArray (str) {
Why not simply `string.split('')`?

2016-12-07 15:13 UTC, badrAZ commented on src/index.js
> +    status: {
I think it's not necessary, i will remove a testSchema and put a default status value.

2016-12-07 15:16 UTC, badrAZ commented on src/index.js
> +      description: 'The snca port'
Yes, i will fix it.

2016-12-07 16:18 UTC, badrAZ commented on src/index.js
> +  _stringToAsciiArray (str) {
I wish convert the string to Ascci code

2016-12-07 16:23 UTC, julien-f requested changes

2016-12-07 16:23 UTC, julien-f commented on src/index.js
> +  _stringToAsciiArray (str) {
`Buffer.from(string, 'ascii')`.

2016-12-07 16:23 UTC, julien-f commented on src/index.js
> +      const dataBuffer = new Buffer(data)
What is the initial type of `data`?
Why creating a new Buffer?

2016-12-13 10:39 UTC, julien-f requested changes

2016-12-13 10:39 UTC, julien-f commented on src/index.js
> +  packet = Buffer.from(packet.toString(encoding), 'ascii')
Why this line???

2016-12-13 10:39 UTC, julien-f commented on src/index.js
> +  let packet = new Buffer(size)
`const`

2016-12-13 10:39 UTC, julien-f commented on src/index.js
> +  let packet = new Buffer(size)
Wouldn't it be possible to automatically compute the size from the arguments?

2016-12-13 10:39 UTC, julien-f commented on src/index.js
> +function nscaPacketBuilder (host, service, size, version, timestamp, iv, status, message, encoding) {
Use named parameters (an object), when there are so many of them.

2016-12-13 10:39 UTC, julien-f commented on src/index.js
> +function xor (long, short) {
I don't like the param names: the second one does not have to be shorter than the first one.

Use `data` and `mask` instead.

2016-12-13 10:39 UTC, julien-f commented on src/index.js
> +  const result = []
Why using an array instead of a buffer?

2016-12-13 10:39 UTC, julien-f commented on src/index.js
> +    if (j === short.length) {
Store the lengths in constants instead of accessing them at each iteration.

2016-12-13 10:39 UTC, julien-f commented on README.md
> +- message: it's the status information in Nagios.
Update the documentation to reflect the named params.

2016-12-13 10:39 UTC, julien-f commented on src/index.js
> +      status: 0,
Export and use named constants:

```js
export const OK = 0
export const WARNING = 1
export const CRITICAL = 2
```

2016-12-13 10:39 UTC, julien-f commented on src/index.js
> +    message
Sort them.

2016-12-13 10:39 UTC, julien-f commented on src/index.js
> +        const iv = Buffer.from(data.toString(encoding, 0, 128), 'ascii') // initialization vector
Avoid converting buffers back and forth.

If you just want a slice: use [`Buffer#slice()`](https://devdocs.io/node~4_lts/buffer#buffer_buf_slice_start_end).

2016-12-13 10:39 UTC, julien-f commented on src/index.js
> +        const key = Buffer.from(this._conf.key, 'ascii')
This could be done once and for all in `configure()`.

2016-12-13 10:39 UTC, julien-f commented on src/index.js
> +        client.write(xorPacketBuffer, (a) => {
Do not use `()` around single param.

2016-12-13 10:39 UTC, julien-f commented on src/index.js
> +      })
You can simplify: `client.on('error', reject)`.

2016-12-13 10:39 UTC, julien-f commented on README.md
> +This xo method is called to send a passive check to nagios and change the status of a service. It has two parameters:
Add a black line between both sentences.

2016-12-13 12:06 UTC, badrAZ commented on src/index.js
> +      const dataBuffer = new Buffer(data)
It's an error, the initial type of data is a buffer. I will fix it.

2016-12-13 12:06 UTC, badrAZ commented on src/index.js
> +  let packet = new Buffer(size)
Nagios ignores all packets size under 720, and when i put a value over 720 i get an invalid CRC 32.

2016-12-13 12:06 UTC, badrAZ commented on src/index.js
> +  const result = []
It's an error, i will fix it.

2016-12-13 12:49 UTC, julien-f commented on src/index.js
> +  let packet = new Buffer(size)
Then the packet size should be 720 but defined directly in this function, no need to pass it as an argument.

2016-12-13 13:23 UTC, badrAZ commented on src/index.js
> +  let packet = new Buffer(size)
ok, i will fix it.

2016-12-13 14:00 UTC, julien-f requested changes

2016-12-13 14:00 UTC, julien-f commented on src/index.js
> +  const result = new Buffer(data.length)
Use `dataSize` here.

2016-12-13 14:00 UTC, julien-f commented on src/index.js
> +        const iv = new Buffer(data.slice(0, 128), ENCODING) // initialization vector
This does not make sense:

- why copying the buffer returned by `slice()`?
- encoding should only be specified when creating a buffer from a string.

2016-12-13 14:00 UTC, julien-f commented on src/index.js
> +  encoding,
How is the encoding a parameter for the function?

What values can be used?

2016-12-13 14:00 UTC, julien-f commented on src/index.js
> +          message: message.toString().replace(/\s/g, ' '),
Why `toString()`? Isn't `message` already a string?

2016-12-13 14:00 UTC, julien-f commented on src/index.js
> +          message: message.toString().replace(/\s/g, ' '),
Why replacing whitespaces by a single space?

2016-12-13 14:00 UTC, julien-f commented on src/index.js
> +  version
Should not be a param, simply use `VERSION`.

2016-12-13 14:00 UTC, julien-f commented on src/index.js
> +        const xorPacketBuffer = new Buffer(
Why are you copying the buffer returned by `xor()`?

2016-12-13 14:00 UTC, julien-f commented on src/index.js
> +          ENCODING
Does not make sense.

2016-12-13 15:02 UTC, badrAZ commented on src/index.js
> +          message: message.toString().replace(/\s/g, ' '),
It's an error, i will fix it.

2016-12-13 15:02 UTC, badrAZ commented on src/index.js
> +          message: message.toString().replace(/\s/g, ' '),
Because Nagios doesn't appreciate a multiple lines in the message.

2016-12-13 15:02 UTC, badrAZ commented on src/index.js
> +        const xorPacketBuffer = new Buffer(
It's an error i will fix it.

2016-12-13 15:05 UTC, badrAZ commented on src/index.js
> +  encoding,
It's an error. I will use the constant instead.

2016-12-13 15:37 UTC, badrAZ commented on src/index.js
> +          message: message.toString().replace(/\s/g, ' '),
After thought, i think it's not necessary  because the message is short.

2016-12-13 15:39 UTC, julien-f commented on src/index.js
> +          message: message.toString().replace(/\s/g, ' '),
If the message should not contain a line break, you should test for it and throw an error.

2016-12-13 15:56 UTC, julien-f requested changes

2016-12-13 15:56 UTC, julien-f commented on src/index.js
> +    if (/\r|\n/.exec(message)) {
Use `RegExp#exec()` to capture substrings or `RegExp#test()` if you just want to validate the string.

2016-12-13 15:56 UTC, julien-f commented on src/index.js
> +      throw new Error('The message must not contain a line break.')
Error messages are not sentences: they should neither start with an upper-case letter nor end with a period.

2016-12-13 17:44 UTC, julien-f requested changes

2016-12-13 17:44 UTC, julien-f commented on src/index.js
> +  packet.writeUInt32BE(crc32.unsigned(packet), 4)
No need to convert to and from an uint32: `crc32()` directly return a buffer.

2016-12-13 17:44 UTC, julien-f commented on src/index.js
> +    const client = new net.Socket()
Move all the code inside the promise to avoid throwing synchronously.

2016-12-14 08:59 UTC, julien-f approved these changes

2016-12-14 09:01 UTC, julien-f commented
@olivierlambert The code is OK for me. What do you think of the functional side?

2016-12-14 09:08 UTC, olivierlambert commented
I'll test on my side. Can you assign me for a review?

2016-12-14 15:33 UTC, olivierlambert approved these changes
LGTM

2016-12-14 15:33 UTC, merged